const data = {
    results: [
      {
        id: 1,
        name: "Luke Skywalker",
        height: "172",
        hair_color: "blond",
        skin_color: "fair",
        eye_color: "blue",
        birth_year: "19BBY",
        gender: "male",
      },
      {
          id: 2,
        name: "C-3PO",
        height: "167",
        hair_color: "n/a",
        skin_color: "gold",
        eye_color: "yellow",
        birth_year: "112BBY",
        gender: "n/a",
      },
      {
          id: 3,
        name: "R2-D2",
        height: "96",
        hair_color: "n/a",
        skin_color: "white, blue",
        eye_color: "red",
        birth_year: "33BBY",
        gender: "n/a",
      },
      {
          id: 4,
        name: "Darth Vader",
        height: "202",
        hair_color: "none",
        skin_color: "white",
        eye_color: "yellow",
        birth_year: "41.9BBY",
        gender: "male",
      },
      {
          id: 5,
        name: "Leia Organa",
        height: "150",
        hair_color: "brown",
        skin_color: "light",
        eye_color: "brown",
        birth_year: "19BBY",
        gender: "female",
      },
      {
          id: 6,
        name: "Owen Lars",
        height: "178",
        hair_color: "brown, grey",
        skin_color: "light",
        eye_color: "blue",
        birth_year: "52BBY",
        gender: "male",
      },
      {
          id: 7,
        name: "Beru Whitesun lars",
        height: "165",
        hair_color: "brown",
        skin_color: "light",
        eye_color: "blue",
        birth_year: "47BBY",
        gender: "female",
      },
      {
          id: 8,
        name: "R5-D4",
        height: "97",
        hair_color: "n/a",
        skin_color: "white, red",
        eye_color: "red",
        birth_year: "unknown",
        gender: "n/a",
      },
      {
          id: 9,
        name: "Biggs Darklighter",
        height: "183",
        hair_color: "black",
        skin_color: "light",
        eye_color: "brown",
        birth_year: "24BBY",
        gender: "male",
      },
      {
          id: 10,
        name: "Obi-Wan Kenobi",
        height: "182",
        hair_color: "auburn, white",
        skin_color: "fair",
        eye_color: "blue-gray",
        birth_year: "57BBY",
        gender: "male",
  
      },
    ]
  };
  
  export default data;
  
  
  